### ISSUE TITLE
Request to release oplus changes in WLAN platform

### ISSUE THREAD

**Issue by chandu078** [OnePlusOSS/android_kernel_modules_and_devicetree_oneplus_sm8550#2]
Hi @OnePlusOSSAdmin,

Kindly, release changes in vendor_qcom_opensource_wlan_platform.

**Comment by chandu078** [comment]
@OnePlusOSSAdmin please don't ignore us

**Comment by OnePlusOSSAdmin** [comment]
This is the qcom codebase information. We are considering how to provide this along with the code release. 
```xml
<project remote="clo-private-la-vendor-13-2-0" name="platform/vendor/qcom-opensource/wlan/fw-api" path="vendor/qcom/opensource/wlan/fw-api" revision="81b6664efd27cf656c6432a6717acbf5c7342668" upstream="refs/heads/wlan-api.lnx.1.0.r107-rel"/>
<project remote="clo-private-la-vendor-13-2-0" name="platform/vendor/qcom-opensource/wlan/qca-wifi-host-cmn" path="vendor/qcom/opensource/wlan/qca-wifi-host-cmn" revision="9510da27dc2b1d6bc95d72381fae712de89cbcc2" upstream="refs/heads/wlan-cmn.driver.lnx.2.0.r61-rel"/>
<project remote="clo-private-la-vendor-13-2-0" name="platform/vendor/qcom-opensource/wlan/qcacld-3.0" path="vendor/qcom/opensource/wlan/qcacld-3.0" revision="79576cfc72bc97b3b42931c28d5bdede86de6e9f" upstream="refs/heads/wlan-cld3.driver.lnx.2.0.r61-rel"/>
<project remote="clo-private-la-vendor-13-2-0" name="platform/vendor/qcom-opensource/wlan/utils/sigma-dut" path="vendor/qcom/opensource/wlan/utils/sigma-dut" revision="566fc5264c417c763e23a6147802c8b763ad7a95" upstream="refs/heads/wlan-service-mcc.lnx.1.0.r3-rel"/>```

**Comment by chandu078** [comment]
The current wlan drivers are not compilable without vendor/qcom/opensource/wlan/platform and I found WPA3 is not working in CLO platform driver,I suspect CNSS issue. Kindly push the platform repo in opensource

**Comment by OnePlusOSSAdmin** [comment]
We'll add this repo with next code update release. It's expected to be released before the end of this month.

**Comment by chandu078** [comment]
Thanks also can you provide a guide for how to compile proper dtbo image in kernel_platform.

**Comment by chandu078** [comment]
> We'll add this repo with next code update release. It's expected to be released before the end of this month.

@OnePlusOSSAdmin any update?

**Comment by OnePlusOSSAdmin** [comment]
@chandu078 Code is ready. It'll be released soon.

**Comment by chandu078** [comment]
> @chandu078 Code is ready. It'll be released soon.

@OnePlusOSSAdmin Please release along with missing below device trees 
bt-devicetree, data-devicetree, eSE-devicetree, graphics-devicetree, mm-devicetree, nfc-devicetree and wlan-devicetree

**Comment by nullptr-t-oss** [comment]
> > @chandu078 Code is ready. It'll be released soon.
> 
> @OnePlusOSSAdmin Please release along with missing below device trees 
> bt-devicetree, data-devicetree, eSE-devicetree, graphics-devicetree, mm-devicetree, nfc-devicetree and wlan-devicetree

Did you manage to compile qcacld3?
