### ISSUE TITLE
Request to release A.23 changes

### ISSUE THREAD

**Issue by areyouanand** [OnePlusOSS/android_kernel_modules_and_devicetree_oneplus_sm8550#3]
Latest publicly available changes are from A.8

**Comment by dekefake** [comment]
@OnePlusOSSAdmin please do not ignore us. Now A24 is released and no code updates have been releaaed since A8

**Comment by OnePlusOSSAdmin** [comment]
Pelase check with the branch oneplus/sm8550_t_13.1.0_oneplus11. It's kernel code for A.24.

**Comment by dekefake** [comment]
Thank you, we appreciate it

**Comment by bgcngm** [comment]
You can close this issue.
