### ISSUE TITLE
Request to release missing device-tree

### ISSUE THREAD

**Issue by chandu078** [OnePlusOSS/android_kernel_modules_and_devicetree_oneplus_sm8550#4]
Hi @OnePlusOSSAdmin, Please release bt-devicetree, data-devicetree, eSE-devicetree, graphics-devicetree, mm-devicetree, nfc-devicetree and wlan-devicetree in opensource, without this devicetree I'm unable to make working dtb and dtbo image.

**Comment by OnePlusOSSAdmin** [comment]
released with the latest code release

**Comment by chandu078** [comment]
Dear @OnePlusOSSAdmin, mm-devicetree is missing. Kindly push in opensource.

**Comment by chandu078** [comment]
Dear @OnePlusOSSAdmin, Please update.

**Comment by chandu078** [comment]
@OnePlusOSSAdmin, please check

**Comment by bgcngm** [comment]
You can close this issue.
