### ISSUE TITLE
Request to release A24 changes

### ISSUE THREAD

**Issue by neobuddy89** [OnePlusOSS/android_kernel_modules_and_devicetree_oneplus_sm8550#5]
Please release A24 changes. Unable to make camera work. Likely changes in kernel.

**Comment by hoangzk9as** [comment]
@OnePlusOSSAdmin Please update code

**Comment by neobuddy89** [comment]
@OnePlusOSSAdmin any plans? why is it taking so much time?

**Comment by chandu078** [comment]
Dear @OnePlusOSSAdmin Kindly update latest code changes along with missing below devicetrees source

bt-devicetree, data-devicetree, eSE-devicetree, graphics-devicetree, mm-devicetree, nfc-devicetree and wlan-devicetree

**Comment by OnePlusOSSAdmin** [comment]
released with a new branch oneplus_sm8550_t_13.1_oneplus11

**Comment by chandu078** [comment]
> released with a new branch oneplus_sm8550_t_13.1_oneplus11

There is no  oneplus_sm8550_t_13.1_oneplus11 branch in android_kernel_modules_and_devicetree_oneplus_sm8550.

![Screenshot_20230811-150916_Chrome](https://github.com/OnePlusOSS/android_kernel_modules_and_devicetree_oneplus_sm8550/assets/68366708/9130f781-eeab-4c28-850f-d70e892ae2e6)

**Comment by OnePlusOSSAdmin** [comment]
It seems that code is not complete, just a update to 13.0 branch. We'll re-release it.  Sorry for the mistake

**Comment by OnePlusOSSAdmin** [comment]
updated. Now 13.1 branch is with full code.

**Comment by bgcngm** [comment]
You can close this issue.
