### ISSUE TITLE
Request for OnePlus Ace 3 (OnePlus 12R)

### ISSUE THREAD

**Issue by cherinyy** [OnePlusOSS/android_kernel_modules_and_devicetree_oneplus_sm8550#8]
Hello @OnePlusOSSAdmin , it seems that you only uploaded [the kernel source code](https://github.com/OnePlusOSS/android_kernel_oneplus_sm8550/tree/oneplus/sm8550_u_14.0.0_ace3) but forgot the module and device tree.

**Comment by OnePlusOSSAdmin** [comment]
Becasue of some large file, it need to be manually dealt with. But engineer is on leave. It need more time to be finished.

**Comment by cherinyy** [comment]
> Becasue of some large file, it need to be manually dealt with. But engineer is on leave. It need more time to be finished.

Okay. Happy Chinese New Year to you all🥳

**Comment by cherinyy** [comment]
https://github.com/OnePlusOSS/android_kernel_modules_and_devicetree_oneplus_sm8550/tree/oneplus/sm8550_u_14.0.0_ace3
